name: Bug report
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      placeholder: Steps, expected vs actual
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
  - type: input
    id: version
    attributes:
      label: Node/PNPM/Next versions
