name: Feature request
description: Propose an enhancement
labels: [enhancement]
body:
  - type: textarea
    id: context
    attributes:
      label: Context / user story
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
